version: '3.8'
services:
  stats-db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: "stats"
      POSTGRES_USER: "stats-admin"
      POSTGRES_PASSWORD: "admin"
      PGPORT: 9091
    ports:
      - "9091:9091"

  stats-server:
    build: "./stats-server"
    ports:
      - "9090:9090"