version: '3.8'
services:
  ewm-service-db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: "main-service"
      POSTGRES_USER: "main-service-admin"
      POSTGRES_PASSWORD: "admin"
      PGPORT: 8081
    ports:
      - "8081:8081"

  ewm-service:
    build: "./main-service/main-service-server"
    ports:
      - "8080:8080"

  stats-db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: "stats"
      POSTGRES_USER: "stats-admin"
      POSTGRES_PASSWORD: "admin"
      PGPORT: 9091
    ports:
      - "9091:9091"

  stats-server:
    build: "./stats/stats-server"
    ports:
      - "9090:9090"