version: '3.1'
services:
  stats-db:
    image: postgres:14-alpine
    ports:
      - "9091:5432"
    environment:
      POSTGRES_USER: "stats-admin"
      POSTGRES_ADMIN: "admin"

  stats-server:
    build: "./stat-server"
    ports:
      - "9090:9090"