CREATE TABLE IF NOT EXISTS users (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY,
        PRIMARY KEY (id),
        email VARCHAR(256) NOT NULL,
        name VARCHAR(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS categories (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY,
        PRIMARY KEY (id),
        name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS events (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY,
        PRIMARY KEY (id),
        annotation TEXT NOT NULL,
        category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
        created_on TIMESTAMP NOT NULL,
        description TEXT NOT NULL,
        event_date TIMESTAMP NOT NULL,
        initiator_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
        location_lat NUMERIC NOT NULL,
        location_lon NUMERIC NOT NULL,
        paid BOOLEAN NOT NULL,
        participant_limit INTEGER NOT NULL,
        published_date TIMESTAMP,
        request_moderation BOOLEAN NOT NULL,
        state TEXT NOT NULL,
        title TEXT NOT NULL,
        views INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS participation_requests (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY,
        PRIMARY KEY (id),
        created_on TIMESTAMP NOT NULL,
        event_id BIGINT REFERENCES events(id) ON DELETE SET NULL,
        requester_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
        status TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS compilations (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY,
        PRIMARY KEY (id),
        pinned BOOLEAN NOT NULL,
        title TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS events_to_compilations (
        event_id BIGINT REFERENCES events(id) ON DELETE CASCADE,
        compilation_id BIGINT REFERENCES compilations(id) ON DELETE CASCADE
);

