CREATE TABLE IF NOT EXISTS stat-record (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY,
        PRIMARY KEY (id),
        app VARCHAR(64) NOT NULL,
        uri VARCHAR(256) NOT NULL,
        ip VARCHAR(64) NOT NULL,
        record-timestamp TIMESTAMP NOT NULL
);